# Generated by Django 5.1.4 on 2024-12-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0002_alter_customuser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
