# Generated by Django 5.1.4 on 2025-01-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0005_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
