# Generated by Django 5.1.4 on 2025-01-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0006_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
