# Generated by Django 5.1.4 on 2025-01-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0009_address_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
    ]
