# Generated by Django 5.1.4 on 2025-01-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0010_remove_cartitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
