# Generated by Django 5.1.4 on 2025-01-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0020_coupon_alter_order_status_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
