# Generated by Django 5.1.4 on 2025-01-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0021_productvariant_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_price',
        ),
    ]
