# Generated by Django 5.1.4 on 2025-01-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0023_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('RETURN_PENDING', 'Return Pending'), ('RETURNED', 'Returned'), ('PAYMENT_PENDING', 'Payment Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('RETURN_PENDING', 'Return pending'), ('RETURNED', 'Returned'), ('PAYMENT_PENDING', 'Payment Pending')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItemReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizing_issues', models.BooleanField(default=False)),
                ('damaged_item', models.BooleanField(default=False)),
                ('incorrect_order', models.BooleanField(default=False)),
                ('delivery_delays', models.BooleanField(default=False)),
                ('other_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_return', to='userr.orderitem')),
            ],
        ),
    ]
