# Generated by Django 5.1.4 on 2025-01-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0024_orderitem_status_alter_order_status_orderitemreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('link', models.CharField(max_length=200)),
                ('position', models.IntegerField(choices=[(1, 'Banner 1 (Top)'), (2, 'Banner 2 (Middle)'), (3, 'Banner 3 (Bottom)')], unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
