# Generated by Django 5.1.4 on 2025-01-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0025_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.IntegerField(choices=[(1, 'Top Banner'), (2, 'Middle Banner'), (3, 'Bottom Banner')], unique=True),
        ),
    ]
