# Generated by Django 5.1.4 on 2025-01-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0026_remove_banner_link_alter_banner_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.IntegerField(choices=[(1, 'Banner 1 (Top)'), (2, 'Banner 2 (Middle)'), (3, 'Banner 3 (Bottom)')], unique=True),
        ),
    ]
