from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_login, name='admin_login'),
    path('dashboard/', views. sales_report, name='admin_dashboard'),
    path('users/', views.user_management, name='user_management'),
    path('products/', views.product_management, name='product_management'),
    path('category/', views.category_list, name='category_management'),
    path('logout/', views.admin_logout, name='admin_logout'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('toggle-user-status/<int:user_id>/', views.toggle_user_status, name='toggle_user_status'),
    path('categories/create/', views.create_category, name='create_category'),
    path('categories/<int:category_id>/edit/', views.edit_category, name='edit_category'),
    path('categories/<int:category_id>/delete/', views.delete_category, name='delete_category'),
    path('categories/<int:category_id>/toggle/', views.toggle_category_status, name='toggle_category_status'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/<int:product_id>/edit/', views.edit_product, name='edit_product'),
    path('products/<int:product_id>/delete/', views.delete_product, name='delete_product'),
    path('products/<int:product_id>/toggle/', views.toggle_product, name='toggle_product'),
    path('add_variant/<int:product_id>/',views.add_variant,name='add_variant'),
    path('manage_variant/<int:product_id>', views.manage_variant, name='manage_variant'),
    path('variant/<int:variant_id>/edit/', views.edit_product_variant, name='edit_variant'),
    path('variant/<int:variant_id>/delete/', views.delete_variant, name='delete_variant'),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('orders/', views.admin_order_list, name='admin_order_list'),
    path('orders_detail/<str:order_no>/', views.admin_order_detail, name='admin_order_detail'),
    path('coupon/',views.coupon_list,name='coupon_list'),
    path('add-coupon/',views.add_coupon,name='add_coupon'),
    path('edit-coupon/<int:pk>/',views.edit_coupon,name='edit_coupon'),
    path('remove-coupon/<int:pk>/',views.remove_coupon,name='remove_coupon'),
    path('offer', views.offer_list,name='offer_list'),
    path('add-offer/', views.add_offer,name='add_offer'),
    path('edit-offer/<int:pk>/', views.edit_offer,name='edit_offer'),
    path('delete-offer/<int:pk>/', views.delete_offer,name='delete_offer'),
    path('manage-item-returns/', views.manage_item_returns, name='manage_returns'),
    path('approve-return-item/<int:return_id>/', views.approve_return_item, name='approve_return_item'),
    path('admin/banners/', views.banner_management, name='banner_management'),
    path('admin/banners/delete/<int:banner_id>/', views.delete_banner, name='delete_banner'),
    path('admin/banners/toggle/<int:banner_id>/', views.toggle_banner, name='toggle_banner'),
]
